import type { MetadataRoute } from 'next';
import { PRODUCT_NAME } from '@/lib/brand';

/**
 * The PWA install manifest (spec §18: offline after first visit, installable).
 * The service worker itself is generated by scripts/prepare-offline.mjs at
 * build time; this declares the app shell so Chromium offers the install
 * prompt. The icon is a hand-authored SVG in public/ — no build step, no
 * binary assets in the repo.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: PRODUCT_NAME,
    short_name: 'SparkLab',
    description: 'The offline-first electronics and Arduino lab: build, simulate, break, learn.',
    start_url: '/builder',
    scope: '/',
    display: 'standalone',
    orientation: 'any',
    background_color: '#0b0e11',
    theme_color: '#00b4d8',
    categories: ['education', 'productivity'],
    icons: [
      { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
      { src: '/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'maskable' },
    ],
  };
}
