import { SiteHeader } from '@/components/SiteHeader';
export const metadata = { title: 'Classroom data and privacy' };
export default function PrivacyPage() {
  return <><SiteHeader /><main id="main" lang="en" className="mx-auto max-w-3xl px-4 py-10 space-y-6">
    <h1 className="text-3xl font-semibold">Classroom data and privacy</h1>
    <p>This describes the software’s data controls, not a claim of legal compliance or a substitute for your school/deployment operator’s privacy notice. Before using accounts with students, the operator must provide its identity, contact details, consent policy, retention period and backup deletion schedule.</p>
    <section className="space-y-3"><h2 className="text-xl font-semibold">What is stored</h2><p>Online accounts store name, verified Google email, Google identity linkage, account role and sign-in sessions. Classrooms store memberships, assignments, submitted native project snapshots, submission times, versions and teacher feedback. Google access, refresh and ID tokens are not retained. Operational request-limit counters are temporary.</p>
      <p>The local builder stores projects on your device. It does not automatically send those projects to a classroom: you explicitly export and upload a snapshot. Do not upload secrets or unnecessary personal information.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Who can see it</h2><p>Classroom owners see their roster and members’ submissions/feedback. Students see only their own work and progress. Students cannot see peer rosters or project snapshots. Classroom APIs do not expose student emails to teachers. Trusted database operators can access stored data and must control and audit their access.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Your controls</h2><ul className="list-disc pl-6 space-y-2"><li>Export your account and submission metadata from the classroom workspace; download project source snapshots separately.</li><li>Leave a classroom to delete your membership and its submissions/feedback.</li><li>Delete your account to remove its sessions, identity linkage, memberships and work. Deleting a teacher’s account also deletes every classroom they own and its students’ work.</li><li>Teachers can remove members and their work, or permanently delete a classroom. Archiving retains records; it is not deletion. Removed members may rejoin using a valid code—replace the code to restrict access.</li></ul></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Retention and limits</h2><p>Records remain in the active database until explicitly deleted; no automatic classroom retention schedule is currently built in. Deletion cascades through the active database immediately upon successful completion. Backups, operator logs and copies already downloaded by a teacher or student are outside these controls. Ask your operator about retention and deletion of those copies.</p><p>Private classroom routes are not stored by the offline service worker. Account deletion does not clear local builder projects or files on your device. Shared devices should be signed out after use.</p></section>
    <a className="btn inline-flex" href="/classrooms">Back to classrooms</a>
  </main></>;
}
